site_name: "Napi Piaci Elemző"
site_description: "Professzionális napi gazdasági elemzések AI támogatással."
site_author: "A Te Neved"
site_url: "https://a-te-weboldalad.hu"

theme:
  name: material
  language: hu
  palette:
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Sötét módra váltás
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Világos módra váltás
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png # (opcionális, később beállítjuk)
  favicon: assets/favicon.ico # (opcionális, később beállítjuk)
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share

plugins:
  - search
  - awesome-pages
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: full

nav:
  - Főoldal: index.md
  - Legfrissebb jelentés: daily/latest.md
  - Archívum: daily/
  - Blog: blog/
  - Kapcsolat: kapcsolat.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/te-fiokod
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/a-te-fiokod