site_name: "Napi Piaci Elemző"
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes

plugins:
  - search
  - awesome-pages

nav:
  - Főoldal: index.md
  - Legfrissebb jelentés: daily/latest.md
  - Jelentések archívum: daily/
  - Blog:
      - Elemzések: blog/elemzesek/
      - Technológia: blog/technologia/
      - Hírek: blog/hirek/
  - Projekt dokumentáció:
      - Technikai leírás: dokumentacio/technikai-leiras.md
      - API dokumentáció: dokumentacio/api-dokumentacio.md
      - GitHub repository: dokumentacio/github.md
      - Közreműködők: dokumentacio/kozremukodok.md
  - Kapcsolat: kapcsolat.md