site_name: "Napi Gazdasági Elemző Rendszer"
theme:
  name: material
  language: hu

nav:
  - Kezdőlap: index.md
  - Napi jelentések: 
      - Legfrissebb jelentés: daily/latest.md

plugins:
  - search